export enum Dota_GameMode {
  ALLPICK = 1,
  CAPTAINS_MODE = 2,
  RANDOM_DRAFT = 3,
  SINGLE_DRAFT = 4,
  ALL_RANDOM = 5,
  // ? intro
  INTRO = 6,

  DIRETIDE = 7,
  REVERSE_CAPTAINS_MODE = 8,
  GREEVILING = 9,
  TUTORIAL = 10,
  MID_ONLY = 11,
  LEAST_PLAYED = 12,
  LIMITED_HEROES = 13,
  BALANCED_DRAFT = 17,
  ABILITY_DRAFT = 18,

  SOLOMID = 21,
  RANKED_AP = 22,
}
