export enum BracketType {
  SINGLE_ELIMINATION = 'SINGLE_ELIMINATION',
  DOUBLE_ELIMINATION = 'DOUBLE_ELIMINATION',
}

export enum TournamentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  REGISTRATION = 'REGISTRATION',
  READY_CHECK = 'READY_CHECK',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
}
